# Generated by Django 3.2.5 on 2021-07-23 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('logo', models.ImageField(upload_to='channel_logo')),
                ('banner', models.ImageField(upload_to='channel_banner')),
                ('about', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UploadVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='thumbnail')),
                ('visibility', models.CharField(choices=[('public', 'public'), ('unlisted', 'unlisted'), ('private', 'private')], max_length=20)),
                ('category', models.CharField(choices=[('Tech', 'Tech'), ('News', 'News'), ('Kids', 'Kids'), ('Eloctronics', 'Eloctronics'), ('Python', 'Python')], max_length=20)),
                ('like', models.IntegerField()),
                ('dislike', models.IntegerField()),
                ('comment_visibility', models.CharField(choices=[('public', 'public'), ('prevent', 'prevent')], max_length=20)),
                ('view_count', models.IntegerField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.channel')),
                ('tag', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
