# Generated by Django 3.2.5 on 2021-07-24 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_auto_20210723_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='uploadvideo',
            name='slug',
        ),
    ]
