# Generated by Django 3.2.5 on 2021-07-24 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        ('studio', '0003_auto_20210724_0549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='user',
        ),
        migrations.AddField(
            model_name='channel',
            name='token',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authtoken.token'),
            preserve_default=False,
        ),
    ]
