# Generated by Django 3.2.5 on 2021-07-24 12:40

from django.db import migrations, models
import studio.models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0004_auto_20210724_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='banner',
            field=models.ImageField(upload_to=studio.models.chnl_banner_upload_path),
        ),
        migrations.AlterField(
            model_name='channel',
            name='logo',
            field=models.ImageField(upload_to=studio.models.chnl_logo_upload_path),
        ),
    ]
