# Generated by Django 3.2.5 on 2021-08-03 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authtoken', '0003_tokenproxy'),
        ('studio', '0007_remove_uploadvideo_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadvideo',
            name='token',
            field=models.ForeignKey(default='ZshefUwd2DN6ND6N7y7NbONfApkLEG1MrEPEKuigSnZ2WEnsEeEa3MR2xQL9CPMj', on_delete=django.db.models.deletion.CASCADE, to='authtoken.token'),
            preserve_default=False,
        ),
    ]
