# Generated by Django 3.2.5 on 2021-08-06 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        ('studio', '0012_alter_subscription_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authtoken.token'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user_channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_channel', to='studio.channel'),
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='which_channels',
        ),
        migrations.AddField(
            model_name='subscription',
            name='which_channels',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='which_channels', to='studio.channel'),
            preserve_default=False,
        ),
    ]
