# Generated by Django 3.2.5 on 2021-08-08 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0017_videodislike_videolike'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videodislike',
            old_name='like',
            new_name='dislike',
        ),
        migrations.RenameField(
            model_name='videolike',
            old_name='dislike',
            new_name='like',
        ),
        migrations.RemoveField(
            model_name='videodislike',
            name='liked_channel',
        ),
        migrations.RemoveField(
            model_name='videodislike',
            name='liked_video',
        ),
        migrations.RemoveField(
            model_name='videolike',
            name='disliked_channel',
        ),
        migrations.RemoveField(
            model_name='videolike',
            name='disliked_video',
        ),
        migrations.AddField(
            model_name='videodislike',
            name='disliked_channel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='disliked_channel', to='studio.channel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videodislike',
            name='disliked_video',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='disliked_video', to='studio.uploadvideo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videolike',
            name='liked_channel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='liked_channel', to='studio.channel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videolike',
            name='liked_video',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='liked_video', to='studio.uploadvideo'),
            preserve_default=False,
        ),
    ]
