# Generated by Django 3.2.5 on 2021-08-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0018_auto_20210808_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
