# Generated by Django 3.2.5 on 2021-08-10 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authtoken', '0003_tokenproxy'),
        ('studio', '0019_channel_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commented_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commented_channel', to='studio.channel')),
                ('received_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_channel', to='studio.channel')),
                ('received_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_video', to='studio.uploadvideo')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authtoken.token')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
