# Generated by Django 3.2.5 on 2021-08-10 23:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studio', '0020_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplayComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('received_parent_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_parent_comment', to='studio.channel')),
                ('replied_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replied_channel', to='studio.channel')),
                ('reply_received_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_received_channel', to='studio.channel')),
                ('reply_received_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_received_video', to='studio.uploadvideo')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authtoken.token')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
