# Generated by Django 3.2.5 on 2021-08-15 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authtoken', '0003_tokenproxy'),
        ('studio', '0022_alter_replaycomment_received_parent_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadvideo',
            name='category',
            field=models.CharField(choices=[('Tech', 'Tech'), ('News', 'News'), ('Kids', 'Kids'), ('Eloctronics', 'Eloctronics'), ('Python', 'Python'), ('Driving', 'Driving'), ('Mahindra thar', 'Mahindra thar'), ('MKBHD', 'MKBHD'), ('Apple', 'Apple'), ('Titan', 'Titan'), ('Bill gates', 'Bill gates'), ('America', 'America'), ('India', 'India'), ('Music', 'Music'), ('TED', 'TED')], max_length=20),
        ),
        migrations.CreateModel(
            name='WatchLater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch_later', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_channel', to='studio.channel')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authtoken.token')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('watch_later_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_later_video', to='studio.uploadvideo')),
            ],
        ),
    ]
