# Generated by Django 3.2.5 on 2021-08-31 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studio', '0025_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResolutionVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_720p', models.FileField(blank=True, null=True, upload_to='video_720p')),
                ('video_480p', models.FileField(blank=True, null=True, upload_to='video_480p')),
                ('video_360p', models.FileField(blank=True, null=True, upload_to='video_360p')),
                ('video_240p', models.FileField(blank=True, null=True, upload_to='video_240p')),
                ('video_144p', models.FileField(blank=True, null=True, upload_to='video_144p')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('og_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='og_video', to=settings.AUTH_USER_MODEL)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authtoken.token')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
