# Generated by Django 3.2.5 on 2021-09-01 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0026_resolutionvideos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resolutionvideos',
            name='og_video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='og_video', to='studio.uploadvideo'),
        ),
    ]
